apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: learnify
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8082"
    spec:
      containers:
        - name: payment-service
          image: docker.io/abdessalem1222/learnify-payment-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: learnify-config
                  key: DB_PAYMENT_URL
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: learnify-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: learnify-config
                  key: EUREKA_SERVER_URL
            - name: SPRING_MAIL_HOST
              valueFrom:
                configMapKeyRef:
                  name: learnify-config
                  key: SPRING_MAIL_HOST
            - name: SPRING_MAIL_PORT
              valueFrom:
                configMapKeyRef:
                  name: learnify-config
                  key: SPRING_MAIL_PORT
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: learnify-secrets
                  key: EMAIL_USERNAME
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: learnify-secrets
                  key: EMAIL_PASSWORD
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,info,prometheus,metrics"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 45
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 90
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: learnify
spec:
  selector:
    app: payment-service
  ports:
    - port: 8082
      targetPort: 8082
