apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: learnify
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8087"
    spec:
      containers:
        - name: user-service
          image: docker.io/abdessalem1222/learnify-user-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8087
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: learnify-config
                  key: DB_USER_URL
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: learnify-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: learnify-config
                  key: EUREKA_SERVER_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: learnify-secrets
                  key: JWT_SECRET
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: learnify-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: learnify-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: learnify-secrets
                  key: SENDGRID_API_KEY
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,info,prometheus,metrics"
          resources:
            requests:
              memory: "384Mi"
              cpu: "250m"
            limits:
              memory: "768Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8087
            initialDelaySeconds: 45
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8087
            initialDelaySeconds: 90
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: learnify
spec:
  selector:
    app: user-service
  ports:
    - port: 8087
      targetPort: 8087
