apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: learnify
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: docker.io/abdessalem1222/learnify-eureka-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: eureka-server
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "false"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: learnify
spec:
  selector:
    app: eureka-server
  type: NodePort
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30761
