spring.application.name=eureka-server
server.port=8761

# Eureka server config
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.wait-time-in-ms-when-sync-empty=0

# If you want web dashboard always accessible locally
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true