# ─────────────────────────────────────────────────────────────────────────────
# IMPORTANT : Remplacez toutes les valeurs REPLACE_ME avant d'appliquer.
# Ne commitez JAMAIS ce fichier avec de vraies valeurs.
# Utilisez : kubectl apply -f secrets.yaml -n learnify
# ─────────────────────────────────────────────────────────────────────────────
apiVersion: v1
kind: Secret
metadata:
  name: learnify-secrets
  namespace: learnify
type: Opaque
stringData:
  # MySQL
  MYSQL_ROOT_PASSWORD: "root"

  # JWT (partagé entre user-service, job-service, preevaluation-service)
  JWT_SECRET: "learnifySecretKeyUltraLongueEtTresSecurisee!"

  # Google Gemini (ai-service)
  GEMINI_API_KEY: "REPLACE_ME"

  # Google OAuth2 (user-service)
  GOOGLE_CLIENT_ID: "REPLACE_ME"
  GOOGLE_CLIENT_SECRET: "REPLACE_ME"

  # SendGrid (user-service)
  SENDGRID_API_KEY: "REPLACE_ME"

  # Groq (preevaluation-service)
  GROQ_API_KEY: "REPLACE_ME"

  # Gmail SMTP (payment-service)
  EMAIL_USERNAME: "REPLACE_ME"
  EMAIL_PASSWORD: "REPLACE_ME"
