apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql-course-db
  namespace: learnify
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-course-db
  namespace: learnify
  labels:
    app: mysql-course-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-course-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-course-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: learnify-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: course_db
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-mysql-course-db
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-course-db
  namespace: learnify
spec:
  selector:
    app: mysql-course-db
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None
